[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ["py37"]

# black compatible isort
[tool.isort]
profile = "black"
