# Generated by Django 3.1.1 on 2020-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='additional_data',
            field=models.TextField(blank=True, null=True, verbose_name='additional data'),
        ),
    ]
