# Generated by Django 3.1.1 on 2020-09-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0008_logentry_additional_data_alter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logentry',
            old_name='additional_data',
            new_name='additional_data_json',
        ),
    ]
