# Generated by Django 2.1.9 on 2020-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0008_auto_20190906_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='path_info',
            field=models.TextField(blank=True, null=True, verbose_name='path info'),
        ),
    ]
