# Generated by Django 3.2.15 on 2022-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0010_alter_logentry_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="changes",
            field=models.JSONField(null=True, verbose_name="change message"),
        ),
    ]
