# Generated by Django 4.0 on 2022-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0014_logentry_cid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logentry",
            name="changes",
            field=models.JSONField(null=True, verbose_name="change message"),
        ),
    ]
