# Generated by Django 3.2.8 on 2025-04-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0015_alter_logentry_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='domain'),
        ),
    ]
