# Generated by Django 3.2.25 on 2024-10-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0015_alter_logentry_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='serialized_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
