# Generated by Django 3.2.19 on 2024-02-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0016_auto_20240210_0934"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logentry",
            old_name="object_repr",
            new_name="object_representation",
        ),
        migrations.RenameField(
            model_name="logentry",
            old_name="object_pk",
            new_name="record",
        ),
    ]
