# Generated by Django 3.2.19 on 2024-02-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auditlog", "0017_auto_20240210_1014"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logentry",
            name="changes_text",
        ),
    ]
