# Generated by Django 2.0.2 on 2018-11-21 11:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='additional_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='additional data'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='change message'),
        ),
    ]
