# Generated by Django 3.0.1 on 2019-12-20 16:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='additional_data_new',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='additional data'),
        ),
    ]
