# Generated by Django 3.0.1 on 2019-12-20 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_convert_json_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='additional_data',
        ),
    ]
